import {
  Home,
  Folder,
  FolderPlus,
  ListTree,
  LayoutGrid,
  GitBranch,
  GitMerge,
  Users,
  FileBarChart,
  Settings,
  FileText,
  FilePlus,
  ClipboardCheck,
  ClipboardList,
  Gauge,
  Activity,
  Share2,
  File,
  Bell,
  HelpCircle,
  ChevronDown,
  ChevronRight,
  Search,
  Send,
  UploadCloud,
  Database,
  Bot,
  Eye,
  BarChart3,
  MoreHorizontal,
  Plus,
  SlidersHorizontal,
  Grid2X2,
  PanelRight,
  Link2,
  Play,
  Pencil,
  RotateCw,
  AlertTriangle,
  CheckCircle2,
  Clock3,
  Calendar,
  ChevronLeft,
  Sparkles,
  Target,
  Swords,
  X,
  Boxes,
  ShieldCheck,
  Route,
  FileCheck2,
  Wand2,
  BrainCircuit,
  CircleDollarSign,
  Lightbulb,
  Layers3,
  Download,
  Paperclip,
  ArrowRight,
  Check,
  XCircle,
  History,
  Star,
  Copy,
  Trash2,
  Archive,
  Presentation,
  Sun,
  Moon,
  Monitor,
  List,
  Upload,
  RotateCcw,
  type LucideIcon,
} from "lucide-react";

const map: Record<string, LucideIcon> = {
  home: Home,
  folder: Folder,
  "folder-plus": FolderPlus,
  "list-tree": ListTree,
  "layout-grid": LayoutGrid,
  "git-branch": GitBranch,
  "git-merge": GitMerge,
  users: Users,
  "file-bar-chart": FileBarChart,
  settings: Settings,
  "file-text": FileText,
  "file-plus": FilePlus,
  "clipboard-check": ClipboardCheck,
  clipboard: ClipboardList,
  gauge: Gauge,
  activity: Activity,
  share: Share2,
  file: File,
  bell: Bell,
  "help-circle": HelpCircle,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  search: Search,
  send: Send,
  "upload-cloud": UploadCloud,
  database: Database,
  bot: Bot,
  eye: Eye,
  "bar-chart": BarChart3,
  more: MoreHorizontal,
  plus: Plus,
  filter: SlidersHorizontal,
  "grid-2": Grid2X2,
  panel: PanelRight,
  link: Link2,
  play: Play,
  pencil: Pencil,
  refresh: RotateCw,
  alert: AlertTriangle,
  "check-circle": CheckCircle2,
  clock: Clock3,
  calendar: Calendar,
  "chevron-left": ChevronLeft,
  sparkles: Sparkles,
  target: Target,
  swords: Swords,
  x: X,
  boxes: Boxes,
  shield: ShieldCheck,
  route: Route,
  "file-check": FileCheck2,
  wand: Wand2,
  brain: BrainCircuit,
  money: CircleDollarSign,
  lightbulb: Lightbulb,
  layers: Layers3,
  download: Download,
  paperclip: Paperclip,
  "arrow-right": ArrowRight,
  check: Check,
  "x-circle": XCircle,
  history: History,
  star: Star,
  copy: Copy,
  trash: Trash2,
  archive: Archive,
  presentation: Presentation,
  sun: Sun,
  moon: Moon,
  monitor: Monitor,
  list: List,
  upload: Upload,
  "rotate-ccw": RotateCcw,
};

export function Icon({
  name,
  className,
  strokeWidth,
}: {
  name: string;
  className?: string;
  strokeWidth?: number;
}) {
  const Cmp = map[name] ?? Folder;
  return <Cmp className={className} strokeWidth={strokeWidth ?? 1.8} />;
}
